# Generated by Django 4.1.2 on 2022-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_users_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_claimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_descr', models.CharField(max_length=255)),
                ('item_picture', models.CharField(max_length=255)),
                ('owner_username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items_on_bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_descr', models.CharField(max_length=255)),
                ('item_picture', models.CharField(max_length=255)),
                ('minimum_bid', models.IntegerField()),
                ('highest_bid', models.IntegerField()),
                ('highest_bidder_username', models.CharField(max_length=255)),
                ('owner_username', models.CharField(max_length=255)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
