# Generated by Django 4.1.3 on 2022-11-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_itemsonbid_rename_items_claimed_itemsclaimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsonbid',
            name='initial_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsonbid',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
    ]
